- hosts: localhost
  become: true
  
  vars_files:
    - vars/main.yml

#  pre_tasks:
#    - name: update repositories
#      apt: update_cache=yes
#      changed_when: False

  roles:
    - role: geerlingguy.mysql
      tags: mysql
    - role: geerlingguy.redis
      tags: redis
    - role: ctfd
      tags: ctfd
    - role: juniorctf
      tags: juniorctf
