---
# tasks file for ctfd


- name: Create CTFd group
  group:
    gid: "{{ ctfd_gid }}"
    name: "{{ ctfd_group }}"

- name: Create CTFd user
  user:
    uid: "{{ ctfd_uid }}"
    name: "{{ ctfd_user }}"
    createhome: no
    home: "{{ ctfd_base_dir }}"
    shell: /sbin/noshell

- name: Clone CTFd repo
  git:
    repo: https://github.com/CTFd/CTFd.git
    dest: "{{ ctfd_base_dir }}"
    force: yes

- name: Install CTFd apt requirements
  apt:
    name:
      - gunicorn
      - authbind

- name: Install CTFd pip requirements
  pip:
    requirements: "{{ ctfd_base_dir }}/requirements.txt"

- name: Set CTFd permissions
  file:
    path: "{{ ctfd_base_dir }}"
    state: directory
    owner: "{{ ctfd_user }}"
    group: "{{ ctfd_group }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Create CTFd config directory
  file:
    path: "{{ ctfd_conf_file | dirname }}"
    state: directory

- name: Store CTFd config
  template:
    src: ctfd.conf
    dest: "{{ ctfd_conf_file }}"
    mode: 0644

- name: CTFd logs directory
  file:
    path: "{{ ctfd_log_dir }}"
    state: directory
    owner: "{{ ctfd_user }}"
    group: "{{ ctfd_group }}"
    mode: 0755

- name: CTFd upload directory
  file:
    path: "{{ ctfd_upload_dir }}"
    state: directory
    owner: "{{ ctfd_user }}"
    group: "{{ ctfd_group }}"
    mode: 0755

- name: Set authbind permissions
  file:
    path: /etc/authbind/byport/80
    state: touch
    owner: "{{ ctfd_user }}"
    mode: 0500

- name: Configure CTFd as a service
  template:
    src: ctfd.service
    dest: "{{ ctfd_service_file }}"

- name: Ensure the CTFd service is enabled and started
  service:
    name: ctfd
    enabled: yes
    state: started

